apiVersion: v1
kind: Secret
metadata:
  name: sinatra-basic-auth
  annotations:
    kubernetes.io/service-account.name: "sa-name"
type: kubernetes.io/basic-auth
stringData:
  username: francklin
  passwors: test1234
  HELLO_MESSAGE: Secret Message!